import { useApp } from '../app-context';
import { Link } from '../router';

export function AboutPage() {
  const { report } = useApp();
  const c = report?.collected;
  return (
    <div className="stack" style={{ maxWidth: 820 }}>
      <h1>About this app</h1>
      <div className="card stack">
        <h2>What it is</h2>
        <p>
          A practice app for the reading part of the Duolingo English Test (DET): <strong>Fill in the Blanks</strong>, <strong>Read and Complete</strong> and{' '}
          <strong>Interactive Reading</strong>, in the DET’s own format, plus vocabulary drills. It is an independent study tool, not made by or connected to Duolingo.
        </p>
        <ul>
          <li>
            <strong>Words:</strong> every word from your two study documents (official DET answer words first), plus words from trusted word lists that match the DET’s
            mostly B1–B2 vocabulary (NGSL, NAWL, CEFR-J, Octanove C1). Words with clear evidence against them were deleted — the list and the reasons are in the{' '}
            <Link to="/report">import report</Link>.
          </li>
          <li>
            <strong>Sentences, texts and passages are real:</strong> they are taken unchanged from openly licensed texts (textbooks, learner news, encyclopedia and
            children’s science articles, stories). Each one shows its source. Every word has one practice sentence; where no suitable real sentence exists, the word
            uses a sentence written for this app, and it is labelled.
          </li>
          <li>
            <strong>Format:</strong> timings, instructions, the letters given, the order of the Interactive Reading questions and the C-test rules follow Duolingo’s
            official Technical Manual (2026) and research reports. By default at most 3 letters are given as the clue (Settings can switch to the DET’s “half the word”).
          </li>
          {c && (
            <li className="small muted">
              In this version: {c.contextOrigins.collected.toLocaleString()} real sentences, {Object.values(c.paragraphsByCorpus).reduce((a, b) => a + b, 0)} real Read
              and Complete texts and {c.interactiveSets} Interactive Reading passages.
            </li>
          )}
        </ul>
      </div>

      <div className="card stack">
        <h2>Why there are no “real” or “repeated” DET questions</h2>
        <p>Many websites sell “real” or “most repeated” DET questions. Duolingo’s own published documents say why these do not exist in a useful way:</p>
        <ul>
          <li>
            Each test is built from a very large bank of items: “any two test sessions are unlikely to share a single item” (DET Technical Manual, 2026). An item is seen
            in only about 1 in 1,000 tests (Settles, LaFlair &amp; Hagiwara, 2020), and items that are seen too often are retired.
          </li>
          <li>
            The items themselves are generated by AI and reviewed by people: Interactive Reading passages and all their questions were “automatically generated by GPT-3”
            and then reviewed (Duolingo Research Report DRR-22-02; Attali et al., 2022).
          </li>
          <li>Test takers promise not to share any test content, and the test’s terms forbid copying it or using it to make preparation material.</li>
        </ul>
        <p>
          What really repeats is the <strong>format</strong> (the task types, instructions and timing), the <strong>kinds of texts</strong> (stories, news and textbook
          passages on everyday and academic topics) and <strong>common vocabulary</strong>, because target words are chosen by frequency. That is exactly what this app
          practises. For official sample questions, use Duolingo’s free practice test and its Practice Questions books — they are copyrighted, so they are linked to, not
          copied.
        </p>
        <p className="small muted">
          No question in this app is guaranteed to appear on the live test.
        </p>
      </div>

      <div className="card stack">
        <h2>How mastery works</h2>
        <ul>
          <li>
            Every word has <strong>one sentence</strong>. Fill in the Blanks and the word drills give you only new words, and each word is asked once.
          </li>
          <li>
            <strong>One correct answer masters a word</strong>: you type it correctly once and it moves to your <Link to="/completed">Completed Checklist</Link>.
          </li>
          <li>
            A wrong, empty or timed-out answer puts the word in your <Link to="/mistakes">Mistake Bank</Link>. It <strong>never comes back by itself</strong>. Fix it in{' '}
            <strong>Practice My Mistakes</strong>, in the same sentence; one correct answer there masters it, and a miss keeps it in the Mistake Bank.
          </li>
          <li>
            There are <strong>no scheduled reviews</strong>: word practice never brings a mastered word back. Only “Review mastered words” (optional, you start it) or
            reopening the word does; a reopened word is new again. A mastered word can still appear in a Read and Complete text or an Interactive Reading passage, and a
            miss there sends it to the Mistake Bank.
          </li>
          <li>A skip is not counted: the word stays new and can come up in a later session.</li>
          <li>
            In Interactive Reading, choosing the right word from options never masters it (only typing does), but a wrong choice is a mistake and sends the word to the
            Mistake Bank. Read and Complete gaps are typed: a correct gap masters the word, a wrong one sends it to the Mistake Bank.
          </li>
        </ul>
      </div>

      <div className="card stack">
        <h2>Where your progress is stored</h2>
        <p>
          In this browser’s IndexedDB database, on this device only. There are no accounts and nothing is sent to a server. Progress survives refreshes and browser
          restarts, but clearing site data, using a private window, or switching device or browser starts fresh. Use <Link to="/settings">Settings → Download backup</Link>{' '}
          to keep a copy or move it to another device.
        </p>
      </div>

      <div className="card stack">
        <h2>Sources and licences</h2>
        <p className="small">
          The texts and lists below are openly licensed. Because some of them are NonCommercial or ShareAlike, this app and its data must stay free and be shared under
          the same terms.
        </p>
        <ul className="small">
          <li>
            <strong>CommonLit CLEAR corpus</strong> (Crossley et al., 2021/2022; corpus CC BY-NC-SA 4.0) — only excerpts whose own licence is CC BY or CC BY-SA: Frontiers
            for Young Minds (CC BY 4.0), Wikipedia and Simple English Wikipedia (CC BY-SA 3.0), African Storybook and others.
          </li>
          <li>
            <strong>OneStopEnglish corpus</strong> (Vajjala &amp; Lučić, 2018), CC BY-SA 4.0 — news texts for learners.
          </li>
          <li>
            <strong>OpenStax textbooks</strong> (Rice University), CC BY-NC-SA 4.0 — Psychology 2e, Introduction to Sociology 3e, Astronomy 2e, Concepts of Biology, U.S.
            History, World History, Introduction to Anthropology, Lifespan Development.
          </li>
          <li>
            <strong>ASSET</strong> (Alva-Manchego et al., 2020), CC BY-NC 4.0, and <strong>CEFR-SP</strong> (Arase, Uchida &amp; Kajiwara, 2022; SCoRE CC BY-NC-SA 4.0,
            Wiki-Auto CC BY-SA 3.0) — single sentences.
          </li>
          <li>
            <strong>Attali et al. (2022)</strong>, “The interactive reading task”, Frontiers in Artificial Intelligence 5:903077, CC BY — the example Interactive Reading
            passage.
          </li>
          <li>
            <strong>Princeton WordNet 3.0</strong> (WordNet licence) — definitions and some example sentences. <strong>wordfreq</strong> (Speer; data CC BY-SA 4.0) — word
            frequencies.
          </li>
          <li>
            <strong>New General Service List 1.2 and New Academic Word List 1.2</strong> (Browne, Culligan &amp; Phillips), CC BY-SA 4.0. <strong>CEFR-J Wordlist 1.5</strong>{' '}
            (compiled by Yukio Tono, Tokyo University of Foreign Studies). <strong>Octanove Vocabulary Profile C1/C2</strong>, CC BY-SA 4.0.
          </li>
          <li>
            <strong>Apertium English–Bengali dictionary</strong> (apertium-bn-en), GPL-2.0 — Bengali meanings marked “dictionary”.
          </li>
          <li>
            DET format facts: Duolingo English Test Technical Manual (2026), research reports DRR-22-02 and DRR-24-01, and the official Question Guide. Duolingo’s
            documents are only cited, not copied.
          </li>
        </ul>
      </div>
    </div>
  );
}
